### ISSUE TITLE
Suggestions for bbcRNA::plot_aln_rates()

### ISSUE THREAD

**Issue by genomics-kl** [vari-bbc/bbcRNA#1]
1. Instead of plotting different data based on the type argument, did you consider creating two different methods? Plotting the number of uniquely mapped reads isn't a rate, so at first glance, the method nomenclature doesn't make sense to me. I think it would be a cleaner interface to have two different methods; ie, plot_aln_reads() and plot_aln_rates(). I suspect you didn't want to duplicate a block of code in (potentially) two similar methods. Perhaps create an internal method containing the code that would normally be duplicated in plot_aln_reads() and plot_aln_rates(). Then, call that internal method from within plot_aln_reads() and plot_aln_rates().

2. Did you consider creating default values for the method arguments facet_by and fill? I think it would be good idea to assign "genotype" as the default argument. Then, you could call the plot* methods just using the bbc_obj. You could, of course, provide alternative arguments if you want. Currently, if the plot_aln_rates() method is called without the facet_by argument, an error is generated.

3. I'd recommend refactoring your method(s) to manipulate the ggplot legend based on a method argument. For example, do something similar to: plot_aln_rates(x=bbc_obj, legend="none").

**Comment by genomics-kl** [comment]
1. 'aln_rates' replaced with 'aln_metrics' throughout entire package.
2. Function was actually written to make 'facet_by' optional, but I accidentally left something in the function that checked for a valid 'facet_by' argument. This has been fixed.
3. To keep the code concise, I am inclined to not put too many options into this and other plotting functions in the package. The relevant portion in the vignette was just to show that the out put can be manipulated like normal ggplot objects. In practice, I think we would usually want to leave the legend in.

**Comment by sgivan** [comment]
As a general philosophy, I don't have a problem with having a lot of options for a function. However, I think that realistic (or the most common) default values should be assigned to every option, if possible. In that way, there could be an unlimited number of options, but none of them are required for the function to finish cleanly.
